[package]
name = "llvm-sys-trial"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "math"
crate-type = ["cdylib"]

[dependencies]
llvm-sys = "60"
